<?xml version="1.0"?>
<package format="2">
  <name>br2_tiago</name>
  <version>0.2.0</version>
  <description>Mastering TIAGo simulated in ROS1 Noetic</description>
  <maintainer email="fmrico@gmail.com">fmrico</maintainer>
  <license>Apache License, Version 2.0</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>tiago_gazebo</exec_depend>
</package>
